name: Unit Tests

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Gtest Unit Tests
    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v1
    - name: configure
      run: cd unit_test && cmake CMakeLists.txt
    - name: make
      run: cd unit_test && make
    - name: Run Test
      run: unit_test/runTests